const KEY='fleetzi-realtime-sim-v2';
const q=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}};
const openAlerts=m=>(m.alerts||[]).filter(a=>!a.ack&&!a.resolved);
const colour=m=>m.status==='dark'||openAlerts(m).some(a=>a.severity==='high')?'#c43d32':openAlerts(m).length?'#e08a17':m.status==='idle'?'#d99b1e':['running','moving'].includes(m.status)?'#23884c':'#69747a';
const label=s=>s==='dark'?'No signal':String(s||'unknown').replace(/^./,c=>c.toUpperCase());
let map=null,ready=false,didFit=false,popup=null,selectedId=null;

function style(){return{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}}
function machinesGeo(s){return{type:'FeatureCollection',features:s.machines.map(m=>({type:'Feature',id:m.id,properties:{id:m.id,asset:m.asset,model:m.model,status:label(m.status),phase:m.phase||'',site:m.site,customer:m.customer,alerts:openAlerts(m).length,colour:colour(m),selected:m.id===selectedId?1:0},geometry:{type:'Point',coordinates:[m.lng,m.lat]}}))}}
function trailsGeo(s){return{type:'FeatureCollection',features:s.machines.filter(m=>(m.trail||[]).length>1).map(m=>({type:'Feature',properties:{id:m.id,selected:m.id===selectedId?1:0,colour:colour(m)},geometry:{type:'LineString',coordinates:(m.trail||[]).slice(-80).map(p=>[p.lng,p.lat])}}))}}
function fitFleet(s){if(!map||!s?.machines?.length)return;const bounds=new maplibregl.LngLatBounds();s.machines.forEach(m=>bounds.extend([m.lng,m.lat]));map.fitBounds(bounds,{padding:{top:45,bottom:45,left:45,right:45},maxZoom:12,duration:650});didFit=true}
function clearSelection(){selectedId=null;popup?.remove();popup=null;const s=read();if(s){update(s);fitFleet(s)}}
function addLayers(s){map.addSource('fleet-trails',{type:'geojson',data:trailsGeo(s)});map.addLayer({id:'fleet-trails',type:'line',source:'fleet-trails',paint:{'line-color':['get','colour'],'line-opacity':['case',['==',['get','selected'],1],.95,.22],'line-width':['case',['==',['get','selected'],1],5,2]}});map.addSource('fleet-machines',{type:'geojson',data:machinesGeo(s)});map.addLayer({id:'fleet-machines',type:'circle',source:'fleet-machines',paint:{'circle-radius':['case',['==',['get','selected'],1],10,7],'circle-color':['get','colour'],'circle-stroke-color':['case',['==',['get','selected'],1],'#2872c7','#ffffff'],'circle-stroke-width':['case',['==',['get','selected'],1],4,2],'circle-opacity':1}});map.addLayer({id:'fleet-labels',type:'symbol',source:'fleet-machines',layout:{'text-field':['get','asset'],'text-size':11,'text-offset':[0,1.35],'text-anchor':'top','text-allow-overlap':false},paint:{'text-color':'#172025','text-halo-color':'#ffffff','text-halo-width':1.5}});
 map.on('mouseenter','fleet-machines',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','fleet-machines',()=>map.getCanvas().style.cursor='');map.on('click','fleet-machines',e=>{const id=e.features?.[0]?.properties?.id,s=read(),m=s?.machines?.find(x=>x.id===id);if(!m)return;selectedId=m.id;update(s);showPopup(m)});}
function showPopup(m){popup?.remove();popup=new maplibregl.Popup({closeButton:true,offset:14}).setLngLat([m.lng,m.lat]).setHTML(`<div class="bb-map-popup"><strong>${esc(m.asset)} · ${esc(m.model)}</strong><span>${esc(label(m.status))} · ${esc(m.phase||'')}</span><span>${esc(m.site)}</span><span>${openAlerts(m).length} open alert${openAlerts(m).length===1?'':'s'}</span><a href="./machine.html?id=${encodeURIComponent(m.id)}&view=live">Open machine →</a></div>`).addTo(map);popup.on('close',()=>{if(selectedId===m.id){selectedId=null;const s=read();if(s)update(s)}})}
function update(s=read()){if(!ready||!s?.machines)return;map.getSource('fleet-machines')?.setData(machinesGeo(s));map.getSource('fleet-trails')?.setData(trailsGeo(s));if(!didFit)fitFleet(s);renderLegend(s)}
function renderLegend(s){let host=q('#dashboard-map-legend');if(!host){host=document.createElement('div');host.id='dashboard-map-legend';host.className='dash-map-legend';q('#dashboard-map-slot')?.prepend(host)}if(!host)return;const active=s.machines.filter(m=>['running','moving'].includes(m.status)).length,idle=s.machines.filter(m=>m.status==='idle').length,attention=s.machines.filter(m=>m.status==='dark'||openAlerts(m).length).length;host.innerHTML=`<span><i class="green"></i>${active} working / moving</span><span><i class="amber"></i>${idle} idle</span><span><i class="red"></i>${attention} attention</span><small>All ${s.machines.length} machines remain visible.</small>${selectedId?'<button id="dashboard-map-overview" type="button">Fleet overview</button>':'<small>Select a marker to inspect a machine.</small>'}`;q('#dashboard-map-overview')?.addEventListener('click',clearSelection)}
function init(){const host=q('#dashboard-map-slot'),s=read();if(!host||!window.maplibregl||!s?.machines)return;host.querySelector('#fleet-map')?.remove();let canvas=q('#dashboard-map-gl');if(!canvas){canvas=document.createElement('div');canvas.id='dashboard-map-gl';canvas.className='sim-map maplibre-fleet-map';host.append(canvas)}map=new maplibregl.Map({container:canvas,style:style(),center:[28.12,-25.97],zoom:9.5,attributionControl:true});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.on('load',()=>{ready=true;addLayers(s);fitFleet(s);renderLegend(s)});map.on('error',e=>console.warn('Fleet map',e.error||e));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setInterval(()=>{if(document.visibilityState==='visible')update()},1000);window.addEventListener('storage',e=>{if(e.key===KEY)update()});