import {STORAGE_KEY,restore} from './model.js';
import {equipmentIntelligence,fleetOverview,mountEquipmentMap,mountFleetMap} from './intelligence-view.js';
const workspace=document.getElementById('workspace'),layout=document.querySelector('.demo-layout');
let syncing=false,lastFleet='';
function state(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?restore(raw):{machines:[],selected:null};}catch{return{machines:[],selected:null};}}
function fleetHost(){let host=document.getElementById('fleet-intelligence');if(!host){host=document.createElement('section');host.id='fleet-intelligence';host.className='fleet-intelligence';host.setAttribute('aria-label','Fleet intelligence overview');layout?.parentNode?.insertBefore(host,layout);}return host;}
function syncFleet(data){const connected=data.machines.filter(m=>m.readings?.position),signature=connected.map(m=>`${m.id}:${m.offline}:${m.readings.position.lat}:${m.readings.position.lng}`).join('|');const host=fleetHost();if(!connected.length){host.hidden=true;host.innerHTML='';lastFleet='';return;}host.hidden=false;if(signature===lastFleet&&host.querySelector('#fleet-map'))return;lastFleet=signature;host.innerHTML=fleetOverview(data.machines);requestAnimationFrame(()=>mountFleetMap(data.machines));host.querySelectorAll('[data-select]').forEach(button=>button.addEventListener('click',()=>document.querySelector(`#equipment-list [data-select="${CSS.escape(button.dataset.select)}"]`)?.click()));}
function syncMachine(data){if(!workspace||workspace.querySelector('.intelligence'))return;const m=data.machines.find(x=>x.id===data.selected);if(!m?.intelligence||!m.readings)return;const anchor=workspace.querySelector('.activity-section')||workspace.querySelector('.record-info:last-of-type');if(!anchor)return;anchor.insertAdjacentHTML('afterend',equipmentIntelligence(m));requestAnimationFrame(()=>mountEquipmentMap(m));}
function sync(){if(syncing)return;syncing=true;try{const data=state();syncFleet(data);syncMachine(data);}finally{syncing=false;}}
const observer=new MutationObserver(()=>queueMicrotask(sync));if(workspace)observer.observe(workspace,{childList:true,subtree:true});const list=document.getElementById('equipment-list');if(list)observer.observe(list,{childList:true,subtree:true});sync();
