const KEY='fleetzi-realtime-sim-v2';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}};
const openAlerts=m=>(m.alerts||[]).filter(a=>!a.ack&&!a.resolved);
const label=s=>s==='dark'?'No signal':String(s||'unknown').replace(/^./,c=>c.toUpperCase());
const colour=m=>m.status==='dark'||openAlerts(m).some(a=>a.severity==='high')?'#c43d32':openAlerts(m).length?'#e08a17':m.status==='idle'?'#d99b1e':['running','moving'].includes(m.status)?'#23884c':'#69747a';
const machineLink=(m,view='overview')=>`./machine.html?id=${encodeURIComponent(m.id)}&view=${encodeURIComponent(view)}`;
let state=read(),map=null,ready=false,selected=null,didFit=false,popup=null;

function mapStyle(){return{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}}
function filtered(){const q=$('#map-search')?.value.trim().toLowerCase()||'',site=$('#map-site')?.value||'all',status=$('#map-status')?.value||'all';return(state?.machines||[]).filter(m=>(site==='all'||m.site===site)&&(status==='all'||m.status===status)&&(!q||[m.asset,m.model,m.type,m.site,m.customer,m.serial].join(' ').toLowerCase().includes(q)))}
function pointFeatures(ms){return{type:'FeatureCollection',features:ms.map(m=>({type:'Feature',id:m.id,properties:{id:m.id,asset:m.asset,model:m.model,status:label(m.status),phase:m.phase||'',site:m.site,customer:m.customer,alerts:openAlerts(m).length,colour:colour(m),selected:m.id===selected?1:0},geometry:{type:'Point',coordinates:[m.lng,m.lat]}}))}}
function routeFeatures(ms){return{type:'FeatureCollection',features:ms.filter(m=>(m.trail||[]).length>1).map(m=>({type:'Feature',properties:{id:m.id,asset:m.asset,colour:colour(m),selected:m.id===selected?1:0},geometry:{type:'LineString',coordinates:(m.trail||[]).slice(-90).map(p=>[p.lng,p.lat])}}))}}
function fitFleet(ms=filtered()){if(!ready||!ms.length)return;const b=new maplibregl.LngLatBounds();ms.forEach(m=>b.extend([m.lng,m.lat]));if(ms.length===1)map.easeTo({center:[ms[0].lng,ms[0].lat],zoom:14,duration:500});else map.fitBounds(b,{padding:{top:50,bottom:50,left:50,right:50},maxZoom:12,duration:650});didFit=true}
function initControls(){const set=(id,key)=>{const el=$(id);if(!el)return;const vals=[...new Set((state?.machines||[]).map(m=>m[key]).filter(Boolean))].sort();vals.forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(key==='status'?label(v):v)}</option>`));el.addEventListener('change',()=>{didFit=false;render()})};set('#map-site','site');set('#map-status','status');$('#map-search')?.addEventListener('input',()=>{didFit=false;render()});$('#map-clear')?.addEventListener('click',()=>{$('#map-search').value='';$('#map-site').value='all';$('#map-status').value='all';selected=null;popup?.remove();popup=null;didFit=false;render()});$('#map-overview')?.addEventListener('click',()=>{selected=null;popup?.remove();popup=null;renderSelection();updateSources();fitFleet()})}
function initMap(){if(map||!window.maplibregl||!$('#live-map-canvas'))return;map=new maplibregl.Map({container:'live-map-canvas',style:mapStyle(),center:[28.12,-25.97],zoom:9.5,attributionControl:true});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.addControl(new maplibregl.FullscreenControl(),'top-right');map.on('load',()=>{ready=true;map.addSource('routes',{type:'geojson',data:routeFeatures(filtered())});map.addLayer({id:'routes',type:'line',source:'routes',paint:{'line-color':['get','colour'],'line-opacity':['case',['==',['get','selected'],1],.95,.2],'line-width':['case',['==',['get','selected'],1],6,2]}});map.addSource('machines',{type:'geojson',data:pointFeatures(filtered())});map.addLayer({id:'machines',type:'circle',source:'machines',paint:{'circle-radius':['case',['==',['get','selected'],1],11,8],'circle-color':['get','colour'],'circle-stroke-color':['case',['==',['get','selected'],1],'#2872c7','#ffffff'],'circle-stroke-width':['case',['==',['get','selected'],1],4,2]}});map.addLayer({id:'machine-labels',type:'symbol',source:'machines',layout:{'text-field':['get','asset'],'text-size':11,'text-offset':[0,1.35],'text-anchor':'top'},paint:{'text-color':'#172025','text-halo-color':'#ffffff','text-halo-width':1.5}});map.on('mouseenter','machines',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','machines',()=>map.getCanvas().style.cursor='');map.on('click','machines',e=>{const id=e.features?.[0]?.properties?.id,m=state?.machines?.find(x=>x.id===id);if(m)selectMachine(m)});fitFleet();render()});}
function selectMachine(m){selected=m.id;renderSelection(m);updateSources();popup?.remove();popup=new maplibregl.Popup({offset:14}).setLngLat([m.lng,m.lat]).setHTML(`<div class="bb-map-popup"><strong>${esc(m.asset)} · ${esc(m.model)}</strong><span>${esc(label(m.status))} · ${esc(m.phase||'')}</span><span>${esc(m.site)}</span><span>${openAlerts(m).length} open alert${openAlerts(m).length===1?'':'s'}</span><a href="${machineLink(m,'live')}">Open machine →</a></div>`).addTo(map);renderResults(filtered())}
function renderSelection(m=state?.machines?.find(x=>x.id===selected)){if(!m){$('#map-selection-title').textContent='Fleet overview';$('#map-selection-sub').textContent='All visible machines remain on the map. Select one to emphasise its recent movement and operating state.';$('#map-selection-actions').innerHTML='';return}$('#map-selection-title').textContent=`${m.asset} · ${m.model}`;$('#map-selection-sub').textContent=`${label(m.status)} · ${m.phase||''} · ${m.site} · ${m.customer} · ${openAlerts(m).length} open alert${openAlerts(m).length===1?'':'s'}`;$('#map-selection-actions').innerHTML=`<a class="ops-link primary" href="${machineLink(m,'live')}">Live</a><a class="ops-link" href="${machineLink(m,'history')}">History</a><a class="ops-link" href="${machineLink(m,'alerts')}">Alerts</a><a class="ops-link" href="${machineLink(m,'maintenance')}">Maintenance</a>`}
function updateSources(){if(!ready)return;const ms=filtered();map.getSource('machines')?.setData(pointFeatures(ms));map.getSource('routes')?.setData(routeFeatures(ms));if(!didFit&&!selected)fitFleet(ms)}
function renderSummary(ms){const active=ms.filter(m=>['running','moving'].includes(m.status)).length,idle=ms.filter(m=>m.status==='idle').length,attention=ms.filter(m=>m.status==='dark'||openAlerts(m).length).length;$('#map-live-summary').innerHTML=`<div><b>${ms.length}</b><span>Visible machines</span></div><div><i class="map-key green"></i><b>${active}</b><span>Working / moving</span></div><div><i class="map-key amber"></i><b>${idle}</b><span>Idle</span></div><div><i class="map-key red"></i><b>${attention}</b><span>Needs attention</span></div><small>All visible routes stay on the map; selection only emphasises one machine.</small>`}
function renderResults(ms){const host=$('#map-results');if(!host)return;host.innerHTML=`<div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>Machine</th><th>Status</th><th>Site</th><th>Customer</th><th>Fuel</th><th>Alerts</th><th>Action</th></tr></thead><tbody>${ms.map(m=>`<tr class="${m.id===selected?'map-selected-row':''}"><td><b>${esc(m.asset)}</b><small>${esc(m.model)}</small></td><td><span class="map-status-dot" style="background:${colour(m)}"></span>${esc(label(m.status))}<small>${esc(m.phase||'')}</small></td><td>${esc(m.site)}</td><td>${esc(m.customer)}</td><td>${Math.round(m.fuel)}%</td><td>${openAlerts(m).length}</td><td><button class="ops-button" data-map-machine="${m.id}" type="button">${m.id===selected?'Selected':'Select'}</button> <a class="ops-link" href="${machineLink(m,'live')}">Open</a></td></tr>`).join('')||'<tr><td colspan="7">No machines match these filters.</td></tr>'}</tbody></table></div>`;document.querySelectorAll('[data-map-machine]').forEach(b=>b.onclick=()=>{const m=state.machines.find(x=>x.id===b.dataset.mapMachine);if(m)selectMachine(m)})}
function render(){state=read();if(!state?.machines){$('#map-results').innerHTML='<div class="ops-empty"><h2>Fleet data unavailable</h2><p>Return to Overview and try again.</p><a class="ops-link primary" href="./demo.html">Return to Overview</a></div>';return}const ms=filtered();renderSummary(ms);renderSelection();updateSources();renderResults(ms)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{initControls();initMap();render()});else{initControls();initMap();render()}setInterval(()=>{if(document.visibilityState==='visible')render()},1000);window.addEventListener('storage',e=>{if(e.key===KEY)render()});