const SIM_KEY='fleetzi-realtime-sim-v2';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
function read(){try{return JSON.parse(localStorage.getItem(SIM_KEY))||null}catch{return null}}
function label(s){return s==='dark'?'No signal':String(s||'unknown').replace(/^./,c=>c.toUpperCase())}
function machineLink(m,view='overview'){return `./machine.html?id=${encodeURIComponent(m.id)}&view=${view}`}
function openAlerts(m){return (m.alerts||[]).filter(a=>!a.ack&&!a.resolved)}
function markerColour(m){if(m.status==='dark'||openAlerts(m).some(a=>a.severity==='high'))return '#c43d32';if(openAlerts(m).length)return '#e08a17';if(m.status==='idle')return '#d99b1e';if(['running','moving'].includes(m.status))return '#23884c';return '#69747a'}
function statusText(m){const alerts=openAlerts(m);return `${label(m.status)}${alerts.length?` · ${alerts.length} open alert${alerts.length===1?'':'s'}`:''}`}
let map=null,markers=new Map(),routeLayers=new Map(),selected=null,state=read(),didInitialFit=false;
function values(key){return [...new Set((state?.machines||[]).map(m=>m[key]))].sort()}
function initControls(){for(const [id,key] of [['#map-site','site'],['#map-status','status']]){const el=$(id);if(!el)continue;values(key).forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(key==='status'?label(v):v)}</option>`));el.addEventListener('change',()=>{selected=null;didInitialFit=false;render()})}$('#map-search')?.addEventListener('input',()=>{didInitialFit=false;render()});$('#map-clear')?.addEventListener('click',()=>{$('#map-search').value='';$('#map-site').value='all';$('#map-status').value='all';selected=null;didInitialFit=false;render()})}
function filtered(){const q=$('#map-search')?.value.trim().toLowerCase()||'',site=$('#map-site')?.value||'all',status=$('#map-status')?.value||'all';return(state?.machines||[]).filter(m=>(site==='all'||m.site===site)&&(status==='all'||m.status===status)&&(!q||[m.asset,m.model,m.type,m.site,m.customer,m.serial].join(' ').toLowerCase().includes(q)))}
function initMap(){if(map||!window.L||!$('#live-map-canvas'))return;map=L.map('live-map-canvas',{zoomControl:true}).setView([-25.97,28.12],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);L.control.scale({imperial:false}).addTo(map)}
function fitFleet(ms){if(!map||!ms.length)return;const pts=[];ms.forEach(m=>{pts.push([m.lat,m.lng]);(m.trail||[]).slice(-24).forEach(p=>pts.push([p.lat,p.lng]))});if(pts.length===1){map.setView(pts[0],15);return}map.fitBounds(L.latLngBounds(pts),{padding:[42,42],maxZoom:13})}
function selectMachine(m){selected=m.id;$('#map-selection-title').textContent=`${m.asset} · ${m.model}`;$('#map-selection-sub').textContent=`${statusText(m)} · ${m.site} · ${m.customer}`;$('#map-selection-actions').innerHTML=`<button id="map-overview" class="ops-button" type="button">Fleet overview</button><a class="ops-link primary" href="${machineLink(m,'live')}">Open live machine</a><a class="ops-link" href="${machineLink(m,'history')}">Movement history</a><a class="ops-link" href="${machineLink(m,'alerts')}">Alerts</a><a class="ops-link" href="${machineLink(m,'maintenance')}">Maintenance</a>`;render();$('#map-overview')?.addEventListener('click',()=>{selected=null;didInitialFit=false;render()})}
function renderRoutes(ms){const visible=new Set(ms.map(m=>m.id));for(const [id,layer] of routeLayers){if(!visible.has(id)){map.removeLayer(layer);routeLayers.delete(id)}}for(const m of ms){const pts=(m.trail||[]).slice(-30).map(p=>[p.lat,p.lng]);let layer=routeLayers.get(m.id);if(pts.length<2){if(layer){map.removeLayer(layer);routeLayers.delete(m.id)}continue}const isSelected=m.id===selected;if(!layer){layer=L.polyline(pts,{lineCap:'round'}).addTo(map);routeLayers.set(m.id,layer)}else layer.setLatLngs(pts);layer.setStyle({color:isSelected?'#2872c7':markerColour(m),weight:isSelected?6:2,opacity:isSelected?.95:.26,dashArray:isSelected?null:'5 5'});if(isSelected)layer.bringToFront()}}
function styleMarkers(){for(const [id,marker] of markers){const m=state?.machines?.find(x=>x.id===id);if(!m)continue;const isSelected=id===selected,colour=markerColour(m);marker.setStyle({radius:isSelected?12:8,weight:isSelected?4:2,color:isSelected?'#2872c7':'#ffffff',fillColor:colour,fillOpacity:1,opacity:1});if(isSelected)marker.bringToFront()}}
function renderMap(ms){initMap();if(!map)return;const visible=new Set(ms.map(m=>m.id));for(const m of state.machines){let marker=markers.get(m.id);if(!marker){marker=L.circleMarker([m.lat,m.lng],{radius:8,weight:2,fillOpacity:1}).addTo(map);marker.on('click',()=>{const latest=state.machines.find(x=>x.id===m.id)||m;selectMachine(latest)});markers.set(m.id,marker)}marker.setLatLng([m.lat,m.lng]);marker.bindTooltip(`<b>${esc(m.asset)} · ${esc(m.model)}</b><br>${esc(statusText(m))}<br>${esc(m.site)}<br>Fuel ${Math.round(m.fuel)}% · ${esc(m.phase||'')}`,{direction:'top'});if(visible.has(m.id)){if(!map.hasLayer(marker))marker.addTo(map)}else if(map.hasLayer(marker))map.removeLayer(marker)}renderRoutes(ms);styleMarkers();if(!didInitialFit){fitFleet(ms);didInitialFit=true}requestAnimationFrame(()=>map.invalidateSize())}
function renderLegend(ms){let host=$('#map-live-summary');if(!host){host=document.createElement('div');host.id='map-live-summary';host.className='map-live-summary';$('#live-map-canvas')?.parentElement?.insertBefore(host,$('#live-map-canvas'))}if(!host)return;const active=ms.filter(m=>['running','moving'].includes(m.status)).length,idle=ms.filter(m=>m.status==='idle').length,attention=ms.filter(m=>openAlerts(m).length||m.status==='dark').length;host.innerHTML=`<div><b>${ms.length}</b><span>Visible machines</span></div><div><i class="map-key green"></i><b>${active}</b><span>Working / moving</span></div><div><i class="map-key amber"></i><b>${idle}</b><span>Idle</span></div><div><i class="map-key red"></i><b>${attention}</b><span>Needs attention</span></div><small>All recent routes stay visible. Select any machine to emphasise its movement without losing fleet context.</small>`}
function renderResults(ms){const host=$('#map-results');if(!host)return;host.innerHTML=`<div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>Machine</th><th>Status</th><th>Site</th><th>Customer</th><th>Fuel</th><th>Open alerts</th><th>Action</th></tr></thead><tbody>${ms.map(m=>`<tr class="${m.id===selected?'map-selected-row':''}"><td><b>${esc(m.asset)}</b><small>${esc(m.model)}</small></td><td><span class="map-status-dot" style="background:${markerColour(m)}"></span>${esc(label(m.status))}<small>${esc(m.phase||'')}</small></td><td>${esc(m.site)}</td><td>${esc(m.customer)}</td><td>${Math.round(m.fuel)}%</td><td>${openAlerts(m).length}</td><td><button class="ops-button" type="button" data-map-machine="${m.id}">${m.id===selected?'Selected':'Show movement'}</button> <a class="ops-link" href="${machineLink(m,'live')}">Open machine</a></td></tr>`).join('')||'<tr><td colspan="7">No machines match these filters.</td></tr>'}</tbody></table></div>`;document.querySelectorAll('[data-map-machine]').forEach(b=>b.onclick=()=>{const m=state.machines.find(x=>x.id===b.dataset.mapMachine);if(m)selectMachine(m)})}
function render(){state=read();if(!state?.machines){const host=$('#map-results');if(host)host.innerHTML='<div class="ops-empty"><p>Open the dashboard first to create simulator state.</p><a class="ops-link primary" href="./demo.html">Open dashboard</a></div>';return}const ms=filtered();renderLegend(ms);renderMap(ms);renderResults(ms);if(selected){const m=state.machines.find(x=>x.id===selected);if(m){$('#map-selection-title').textContent=`${m.asset} · ${m.model}`;$('#map-selection-sub').textContent=`${statusText(m)} · ${m.site} · ${m.customer} · ${Number(m.lat).toFixed(5)}, ${Number(m.lng).toFixed(5)}`;if(!$('#map-overview'))$('#map-selection-actions').insertAdjacentHTML('afterbegin','<button id="map-overview" class="ops-button" type="button">Fleet overview</button>');$('#map-overview')?.addEventListener('click',()=>{selected=null;didInitialFit=false;$('#map-selection-title').textContent='Fleet overview';$('#map-selection-sub').textContent='All visible machines and recent movement';$('#map-selection-actions').innerHTML='';render()})}}else{$('#map-selection-title').textContent='Fleet overview';$('#map-selection-sub').textContent=`${ms.length} machines · recent movement shown for every visible machine`;$('#map-selection-actions').innerHTML=''}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{initControls();render();setInterval(render,1000)});else{initControls();render();setInterval(render,1000)}
window.addEventListener('storage',e=>{if(e.key===SIM_KEY)render()});