const KEY='fleetzi-realtime-sim-v2';
const sites={
 'Midrand Earthworks':{lat:-25.9992,lng:28.1263},
 'Waterfall Bulk Works':{lat:-26.0148,lng:28.1054},
 'Kyalami Roadworks':{lat:-25.9901,lng:28.0738},
 'Centurion Platform Works':{lat:-25.8674,lng:28.1892}
};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function read(){try{const s=JSON.parse(localStorage.getItem(KEY));return s?.version===2?s:null}catch{return null}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function minute(s){const d=new Date(s.clock);return d.getHours()*60+d.getMinutes()}
function phase(m,min){const r=min-m.shiftStart;if(r<0)return'prestart';if(r<20)return'mobilising';if(r<150)return'productive';if(r<190)return'break';if(r<390)return'productive';if(r<430)return'winddown';if(min<m.shiftEnd)return'productive';return'shutdown'}
function time(s){return new Intl.DateTimeFormat('en-ZA',{hour:'2-digit',minute:'2-digit'}).format(new Date(s.clock))}
function stamp(s){return new Intl.DateTimeFormat('en-ZA',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(s.clock))}
function event(m,s,type,text){if(m.lastPhase===text)return;m.events=m.events||[];m.events.unshift({time:time(s),type,text});m.events=m.events.slice(0,60)}
function setPhase(m,s,p){if(m.lastPhase===p)return;m.lastPhase=p;m.phase=p;const text={prestart:'Awaiting shift start',mobilising:'Mobilising to work area',productive:'Productive operating window',break:'Scheduled break / standby',winddown:'End-of-shift wind-down',shutdown:'Shift complete'}[p];m.events=m.events||[];m.events.unshift({time:time(s),type:'operation',text});m.events=m.events.slice(0,60)}
function raise(m,s,type,text,severity='medium'){m.alerts=m.alerts||[];if(m.alerts.some(a=>!a.ack&&!a.resolved&&a.type===type&&a.text===text))return;const a={id:`${m.id}-${s.tick}-${type}`,time:stamp(s),type,text,severity,ack:false};m.alerts.unshift(a);m.alerts=m.alerts.slice(0,30);m.events.unshift({time:time(s),type:'alert',text});m.exception={type,text,severity,ack:false};m.exceptionStarted=s.clock}
function operate(m,status){m.status=status;m.signal='Live';m.speed=status==='moving'?6+(Number(m.id.slice(1))%5):0;if(['running','moving','idle'].includes(status)){m.meter+=1/60;m.fuel=clamp(m.fuel-(status==='idle'?.035:.075),0,100);const d=m.history.at(-1);d.run=+(d.run+1/60).toFixed(2);if(status==='idle')d.idle=+(d.idle+1/60).toFixed(2);d.working=+Math.max(0,d.run-d.idle).toFixed(2);d.meter=+m.meter.toFixed(2)}m.engineLoad=m.engineLoad==null?m.engineLoad:(status==='off'?0:status==='idle'?22:status==='moving'?58:68);if(m.coolant!=null)m.coolant=status==='off'?64:status==='idle'?77:88}
function moveInside(m,s){const site=sites[m.site];if(!site)return;const a=(s.tick*7+Number(m.id.slice(1))*40)%360*Math.PI/180,r=.0011+(Number(m.id.slice(1))%3)*.00025;m.lat=site.lat+Math.cos(a)*r;m.lng=site.lng+Math.sin(a)*r;m.inside=true}
function leave(m){const site=sites[m.site];if(!site)return;m.lat=site.lat+Math.cos(1.2)*.0062;m.lng=site.lng+Math.sin(1.2)*.0062;m.inside=false}
function scenario(m,s,p){const since=minute(s)-m.shiftStart;if(m.scenario==='connectivity'&&since>=115&&since<145){m.status='dark';m.signal='No signal';m.speed=0;if(!m.exception||m.exception.ack)raise(m,s,'connectivity','No telemetry received during active hire','high');return true}if(m.scenario==='geofence-risk'&&since>=245&&since<285){operate(m,'moving');leave(m);if(!m.exception||m.exception.ack)raise(m,s,'geofence',`Left permitted site: ${m.site}`,'high');return true}if(m.scenario==='idle-risk'&&since>=210&&since<255){operate(m,'idle');if(since>=225&&(!m.exception||m.exception.ack))raise(m,s,'idle','Excessive idle time: 15+ minutes during hire','medium');return true}if(m.scenario==='service-risk'&&m.nextService-m.meter<=50&&(!m.exception||m.exception.ack))raise(m,s,'maintenance',`Service due in ${Math.max(0,Math.round(m.nextService-m.meter))} h`,'medium');return false}
function stepMachine(m,s){const p=phase(m,minute(s));setPhase(m,s,p);if(!scenario(m,s,p)){if(p==='prestart'||p==='shutdown')operate(m,'off');else if(p==='mobilising'){operate(m,'moving');moveInside(m,s)}else if(p==='break')operate(m,m.scenario==='standby'?'off':'idle');else if(p==='winddown')operate(m,'idle');else if(p==='productive'){if(m.scenario==='standby')operate(m,'off');else if(m.scenario==='haul'){operate(m,'moving');moveInside(m,s)}else{const cycle=(s.tick+Number(m.id.slice(1))*3)%18;operate(m,cycle<3?'idle':cycle<7?'moving':'running');if(m.status==='moving')moveInside(m,s)}}}if(m.fuel<20)raise(m,s,'fuel',`Fuel low at ${Math.round(m.fuel)}%`,'medium');if(m.meter>=m.nextService)raise(m,s,'maintenance',`Service overdue by ${Math.round(m.meter-m.nextService)} h`,'high');if(s.tick%2===0&&m.signal==='Live'){m.trail=m.trail||[];m.trail.push({ts:s.clock,t:time(s),lat:m.lat,lng:m.lng});m.trail=m.trail.slice(-180)}m.sensor=m.sensor||[];m.sensor.push({time:time(s),fuel:+m.fuel.toFixed(1),temp:m.coolant});m.sensor=m.sensor.slice(-80);const h=m.hire?.[0];if(h){h.meterEnd=+m.meter.toFixed(2);h.measured=+(h.meterEnd-h.meterStart).toFixed(2);h.proposed=Math.max(h.minimum,Math.ceil(h.measured*4)/4);if(p==='shutdown'&&h.status!=='Approved')h.status='Needs review'}}
function tick(){const s=read();if(!s||!s.running)return;s.clock+=60000;s.tick=(s.tick||0)+1;s.machines.forEach(m=>stepMachine(m,s));save(s)}
setInterval(tick,1000);