const SIM_KEY='fleetzi-realtime-sim-v1';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
let movementMap=null;
let movementLayers=[];
let detailObserverBusy=false;

function readState(){try{return JSON.parse(localStorage.getItem(SIM_KEY))||null}catch{return null}}
function norm(v){return String(v??'').toLowerCase().trim()}
function machineText(m){return [m.asset,m.type,m.model,m.serial,m.year,m.site,m.customer,m.attachment,m.status].map(norm).join(' ')}
function matches(m,q){return !q||machineText(m).includes(norm(q))}

function ensureSearch(){const controls=$('.sim-controls');if(!controls||$('#fleet-search'))return;const box=document.createElement('div');box.className='fleet-search';box.innerHTML=`<label for="fleet-search">Search fleet<input id="fleet-search" type="search" autocomplete="off" placeholder="Asset, model, serial, site or customer"><span class="search-hint">Searches all 12 simulated machines</span></label><div id="fleet-search-results" class="fleet-search-results" hidden></div>`;controls.prepend(box);const input=$('#fleet-search');input.addEventListener('input',()=>{applySearch(input.value);renderSearchResults(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';applySearch('');renderSearchResults('');}});document.addEventListener('click',e=>{if(!box.contains(e.target))$('#fleet-search-results').hidden=true});}

function applySearch(query){const q=norm(query);$$('#machine-table tbody tr[data-id]').forEach(row=>{const state=readState(),m=state?.machines?.find(x=>x.id===row.dataset.id);row.hidden=!!m&&!matches(m,q)});const visible=$$('#machine-table tbody tr[data-id]:not([hidden])').length;let count=$('#fleet-search-count');if(!count){count=document.createElement('span');count.id='fleet-search-count';count.className='fleet-search-count';$('.sim-card-head h2')?.parentElement?.append(count)}if(count)count.textContent=q?`${visible} matching machine${visible===1?'':'s'}`:'';}

function renderSearchResults(query){const host=$('#fleet-search-results'),state=readState();if(!host||!state)return;const q=norm(query);if(!q){host.hidden=true;host.innerHTML='';return;}const found=state.machines.filter(m=>matches(m,q)).slice(0,8);host.innerHTML=found.length?found.map(m=>`<button type="button" data-search-machine="${m.id}"><b>${m.asset} · ${m.model}</b><span>${m.type} · ${m.site}</span><small>${m.customer} · ${m.serial}</small></button>`).join(''):'<p>No machine matches that search.</p>';host.hidden=false;$$('[data-search-machine]').forEach(btn=>btn.onclick=()=>openMachine(btn.dataset.searchMachine));}

function openMachine(id){const input=$('#fleet-search');$('#clear-filters')?.click();if(input){input.value='';applySearch('');renderSearchResults('');}setTimeout(()=>{const row=$(`#machine-table tbody tr[data-id="${CSS.escape(id)}"]`);if(row){row.click();row.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>$('#machine-detail')?.scrollIntoView({behavior:'smooth',block:'start'}),120);}},30);}

function enhanceRows(){const th=$('#machine-table thead tr');if(th&&!th.querySelector('.open-col')){const cell=document.createElement('th');cell.className='open-col';cell.textContent='Open';th.append(cell)}$$('#machine-table tbody tr[data-id]').forEach(row=>{if(row.querySelector('.open-machine'))return;const td=document.createElement('td');td.className='open-col';const b=document.createElement('button');b.type='button';b.className='open-machine';b.textContent='View';b.setAttribute('aria-label',`Open ${row.querySelector('b')?.textContent||'machine'} details`);b.onclick=e=>{e.stopPropagation();row.click()};td.append(b);row.append(td)});const q=$('#fleet-search')?.value||'';if(q)applySearch(q);}

function pointDistanceKm(a,b){const r=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng),la1=toRad(a.lat),la2=toRad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(h))}
function trailDistance(points){let total=0;for(let i=1;i<points.length;i++)total+=pointDistanceKm(points[i-1],points[i]);return total}
function sliceTrail(trail,range){if(range==='30m')return trail.slice(-15);if(range==='2h')return trail.slice(-60);return trail.slice();}

function movementCard(m){return `<section id="movement-history-card" class="movement-history-card"><div class="movement-head"><div><span class="eyebrow">MOVEMENT HISTORY</span><h3>Where ${m.asset} has been</h3><p>Select a period to redraw the route. Each point is simulated telemetry with a timestamp.</p></div><div class="movement-ranges" role="group" aria-label="Movement history range"><button type="button" data-movement-range="30m">Last 30 min</button><button type="button" data-movement-range="2h" class="active">Last 2 h</button><button type="button" data-movement-range="all">All available</button></div></div><div class="movement-summary" id="movement-summary"></div><div id="movement-history-map" class="movement-history-map" aria-label="Selected machine movement history map"></div><div id="movement-timeline" class="movement-timeline"></div></section>`}

function injectMovement(){if(detailObserverBusy)return;const host=$('#machine-detail'),state=readState();if(!host||!state||host.querySelector('#movement-history-card'))return;const m=state.machines.find(x=>x.id===state.selected);if(!m)return;detailObserverBusy=true;const tabs=host.querySelector('.detail-tabs');if(tabs)tabs.insertAdjacentHTML('beforebegin',movementCard(m));else host.insertAdjacentHTML('beforeend',movementCard(m));$$('[data-movement-range]').forEach(b=>b.onclick=()=>{$$('[data-movement-range]').forEach(x=>x.classList.toggle('active',x===b));drawMovement(m,b.dataset.movementRange)});requestAnimationFrame(()=>drawMovement(m,'2h'));detailObserverBusy=false;}

function clearMovementMap(){movementLayers.forEach(l=>{try{movementMap?.removeLayer(l)}catch{}});movementLayers=[]}
function drawMovement(machine,range){const host=$('#movement-history-map');if(!host||!window.L)return;const state=readState(),m=state?.machines?.find(x=>x.id===machine.id)||machine;const points=sliceTrail(m.trail||[],range);if(!movementMap){movementMap=L.map(host,{zoomControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(movementMap)}clearMovementMap();if(!points.length)return;const coords=points.map(p=>[p.lat,p.lng]);const line=L.polyline(coords,{weight:4,opacity:.85}).addTo(movementMap);movementLayers.push(line);const start=L.circleMarker(coords[0],{radius:6,weight:2,fillOpacity:1}).addTo(movementMap).bindTooltip(`Start · ${points[0].t||''}`);const end=L.circleMarker(coords.at(-1),{radius:7,weight:2,fillOpacity:1}).addTo(movementMap).bindTooltip(`Latest · ${points.at(-1).t||''}`);movementLayers.push(start,end);points.forEach((p,i)=>{if(i===0||i===points.length-1||i%10)return;const dot=L.circleMarker([p.lat,p.lng],{radius:3,weight:1,fillOpacity:.75}).addTo(movementMap).bindTooltip(p.t||`Point ${i+1}`);movementLayers.push(dot)});movementMap.fitBounds(line.getBounds(),{padding:[24,24],maxZoom:16});requestAnimationFrame(()=>movementMap.invalidateSize());const distance=trailDistance(points);const summary=$('#movement-summary');if(summary)summary.innerHTML=`<div><span>Period</span><b>${range==='30m'?'Last 30 minutes':range==='2h'?'Last 2 hours':'All available movement'}</b></div><div><span>Telemetry points</span><b>${points.length}</b></div><div><span>Route distance</span><b>${distance.toFixed(2)} km</b></div><div><span>From → to</span><b>${points[0].t||'Start'} → ${points.at(-1).t||'Latest'}</b></div>`;const timeline=$('#movement-timeline');if(timeline)timeline.innerHTML=`<h4>Route timeline</h4><ol>${points.slice().reverse().slice(0,12).map((p,i)=>`<li><time>${p.t||'—'}</time><span>${i===0?'Latest position':'Movement point'}</span><small>${Number(p.lat).toFixed(5)}, ${Number(p.lng).toFixed(5)}</small></li>`).join('')}</ol>`;}

function observe(){ensureSearch();enhanceRows();injectMovement();const table=$('#machine-table tbody');if(table)new MutationObserver(()=>{enhanceRows();const q=$('#fleet-search')?.value||'';if(q)applySearch(q)}).observe(table,{childList:true});const detail=$('#machine-detail');if(detail)new MutationObserver(()=>{if(movementMap){try{movementMap.remove()}catch{}movementMap=null;movementLayers=[]}queueMicrotask(injectMovement)}).observe(detail,{childList:true,subtree:false});}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();