const SIM_KEY='fleetzi-realtime-sim-v2';
const ACTION_KEY='fleetzi-realtime-actions-v2';
const sites={
  midrand:{name:'Midrand Earthworks',lat:-25.9992,lng:28.1263,radius:.0045},
  waterfall:{name:'Waterfall Bulk Works',lat:-26.0148,lng:28.1054,radius:.0045},
  kyalami:{name:'Kyalami Roadworks',lat:-25.9901,lng:28.0738,radius:.004},
  centurion:{name:'Centurion Platform Works',lat:-25.8674,lng:28.1892,radius:.0045}
};
const seed=[
['EX-001','Excavator','CAT 320','CAT0320EX001',2022,'Midrand Earthworks','Example Civil Co.','Bucket + hydraulic hammer',950,2847,3000,72,'production'],
['ADT-014','Articulated dump truck','Bell B30E','BELLB30E014',2021,'Waterfall Bulk Works','Metro Earthworks','Standard body',1250,4958,5000,49,'haul'],
['TLB-002','Backhoe loader','JCB 3DX','JCB3DX002',2020,'Kyalami Roadworks','Example Roads JV','4-in-1 bucket',780,1734,1900,61,'connectivity'],
['ROL-007','Roller','BOMAG BW 213','BOM213007',2023,'Centurion Platform Works','Civils Demo Ltd','Smooth drum',820,2216,2400,54,'idle-risk'],
['DZ-005','Dozer','Komatsu D65','KOMD65005',2019,'Midrand Earthworks','Example Civil Co.','Straight blade',1100,6118,6250,66,'service-risk'],
['WL-011','Wheel loader','Volvo L90H','VOL90H011',2022,'Waterfall Bulk Works','Metro Earthworks','General purpose bucket',1050,3211,3400,58,'production'],
['EX-009','Excavator','Hitachi ZX210','HTZX210009',2018,'Kyalami Roadworks','Example Roads JV','Trenching bucket',920,7881,8000,43,'geofence-risk'],
['GR-003','Motor grader','CAT 140K','CAT140K003',2017,'Centurion Platform Works','Civils Demo Ltd','Mouldboard',1180,9044,9200,70,'production'],
['SK-021','Skid steer','Bobcat S650','BOBS650021',2024,'Midrand Earthworks','Example Civil Co.','Pallet forks',620,842,1000,81,'idle-risk'],
['CR-004','Crawler crane','Liebherr LR 1160','LIE1160004',2020,'Waterfall Bulk Works','Metro Earthworks','Main boom',2250,4120,4300,77,'standby'],
['TLB-018','Backhoe loader','CAT 428F2','CAT428018',2021,'Centurion Platform Works','Civils Demo Ltd','Backhoe + loader',800,2651,2800,52,'production'],
['EX-016','Excavator','Komatsu PC210','KOMPC21016',2023,'Kyalami Roadworks','Example Roads JV','Rock bucket',980,1191,1350,64,'haul']
];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const fmt=n=>Number.isFinite(n)?Number(n).toFixed(1):'—';
const nowTime=d=>new Intl.DateTimeFormat('en-ZA',{hour:'2-digit',minute:'2-digit'}).format(d);
const nowLabel=d=>new Intl.DateTimeFormat('en-ZA',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d);
function siteByName(name){return Object.values(sites).find(s=>s.name===name)||Object.values(sites)[0]}
function offsetPoint(site,i,scale=.0015){const a=(i*67)%360*Math.PI/180;return{lat:site.lat+Math.cos(a)*scale,lng:site.lng+Math.sin(a)*scale}}
function makeHistory(meter,i){const out=[];let h=meter-36;for(let d=6;d>=0;d--){const run=5.2+((i+d)%5)*.55,idle=.6+((i+d*2)%4)*.3;h+=run;out.push({date:new Date(Date.now()-d*86400000).toLocaleDateString('en-ZA',{day:'2-digit',month:'short'}),run:+run.toFixed(1),idle:+idle.toFixed(1),working:+Math.max(0,run-idle).toFixed(1),meter:+h.toFixed(1),fuelUsed:+(run*(5.5+(i%3))).toFixed(1)})}return out}
function makeMachine(row,i){const [asset,type,model,serial,year,siteName,customer,attachment,rate,meter,nextService,fuel,scenario]=row;const site=siteByName(siteName),p=offsetPoint(site,i);return{
 id:'m'+i,asset,type,model,serial,year,site:siteName,customer,attachment,rate,meter,nextService,fuel,scenario,
 shiftStart:420+(i%4)*15,shiftEnd:1020-(i%3)*15,phase:'prestart',status:'off',signal:'Live',lat:p.lat,lng:p.lng,homeLat:p.lat,homeLng:p.lng,heading:(i*31)%360,speed:0,
 engineLoad:type==='Crawler crane'?null:0,coolant:type==='Skid steer'?null:62,faultCodes:i===6?['SPN 111 FMI 3']:[],lastService:new Date(Date.now()-(35+i*4)*86400000).toLocaleDateString('en-ZA'),
 history:makeHistory(meter,i),trail:[{ts:Date.now()-7200000,t:'07:00',lat:p.lat-.0008,lng:p.lng-.0007},{ts:Date.now()-3600000,t:'08:00',lat:p.lat-.0003,lng:p.lng-.0002},{ts:Date.now(),t:'Now',lat:p.lat,lng:p.lng}],
 events:[{time:'07:00',type:'assignment',text:`Assigned to ${siteName}`},{time:'07:05',type:'prestart',text:'Pre-start check completed'}],alerts:[],maintenance:[{date:new Date(Date.now()-(50+i*2)*86400000).toLocaleDateString('en-ZA'),work:'Scheduled service completed',meter:Math.round(meter-180),status:'Completed'}],
 hire:[{date:'Today',meterStart:+meter.toFixed(1),meterEnd:+meter.toFixed(1),measured:0,minimum:8,proposed:8,status:'Collecting evidence'}],sensor:[{time:'07:00',fuel,temp:null}],inside:true,exception:null,exceptionStarted:null,lastPhase:null
}}
function initialState(){const start=new Date();start.setHours(7,0,0,0);return{version:2,clock:start.getTime(),running:true,machines:seed.map(makeMachine),selected:null,filters:{site:'all',type:'all',status:'all',customer:'all'},tick:0}}
function load(){try{const x=JSON.parse(localStorage.getItem(SIM_KEY));if(x?.version===2&&x?.machines?.length===12)return x}catch{}return initialState()}
let state=load();let map,markers=new Map(),trailLayer,geofenceLayers=[];
function save(){localStorage.setItem(SIM_KEY,JSON.stringify(state))}
function actions(){try{return JSON.parse(localStorage.getItem(ACTION_KEY))||[]}catch{return[]}}
function logAction(action,machine,subject){if(!machine)return;const list=actions();list.unshift({time:nowLabel(new Date(state.clock)),action,machine:{id:machine.id,asset:machine.asset},subject,actor:'Fleet manager'});localStorage.setItem(ACTION_KEY,JSON.stringify(list.slice(0,100)));if(action==='Acknowledge'&&machine.exception)machine.exception.ack=true;if(action==='Schedule service')machine.maintenance.unshift({date:new Date(state.clock).toLocaleDateString('en-ZA'),work:'Service work order scheduled',meter:Math.round(machine.meter),status:'Scheduled'});toast(`${action}: ${machine.asset}`);save();renderAll()}
function minuteOfDay(){const d=new Date(state.clock);return d.getHours()*60+d.getMinutes()}
function phaseFor(m,minute){const r=minute-m.shiftStart;if(r<0)return'prestart';if(r<20)return'mobilising';if(r<150)return'productive';if(r<190)return'break';if(r<390)return'productive';if(r<430)return'winddown';if(minute<m.shiftEnd)return'productive';return'shutdown'}
function setPhase(m,phase){if(m.lastPhase===phase)return;m.lastPhase=phase;m.phase=phase;const labels={prestart:'Awaiting shift start',mobilising:'Mobilising to work area',productive:'Productive operating window',break:'Scheduled break / standby',winddown:'End-of-shift wind-down',shutdown:'Shift complete'};m.events.unshift({time:nowTime(new Date(state.clock)),type:'operation',text:labels[phase]});m.events=m.events.slice(0,60)}
function raise(m,type,text,severity='medium'){if(m.alerts.some(a=>!a.ack&&a.type===type&&a.text===text))return;const a={id:`${m.id}-${state.tick}-${type}`,time:nowLabel(new Date(state.clock)),type,text,severity,ack:false};m.alerts.unshift(a);m.alerts=m.alerts.slice(0,30);m.events.unshift({time:nowTime(new Date(state.clock)),type:'alert',text});m.exception={type,text,severity,ack:false};m.exceptionStarted=state.clock}
function operate(m,status){m.status=status;m.signal='Live';m.speed=status==='moving'?6+(m.id.charCodeAt(1)%5):0;if(['running','moving','idle'].includes(status)){m.meter+=1/60;m.fuel=clamp(m.fuel-(status==='idle'?.035:.075),0,100);const today=m.history.at(-1);today.run=+(today.run+1/60).toFixed(2);if(status==='idle')today.idle=+(today.idle+1/60).toFixed(2);today.working=+Math.max(0,today.run-today.idle).toFixed(2);today.meter=+m.meter.toFixed(2)}m.engineLoad=m.engineLoad===null?null:(status==='off'?0:status==='idle'?22:status==='moving'?58:68);if(m.coolant!==null)m.coolant=status==='off'?64:status==='idle'?77:88}
function moveInsideSite(m){const s=siteByName(m.site),angle=(state.tick*7+Number(m.id.slice(1))*40)%360*Math.PI/180,r=.0011+(Number(m.id.slice(1))%3)*.00025;m.lat=s.lat+Math.cos(angle)*r;m.lng=s.lng+Math.sin(angle)*r;m.inside=true}
function leaveSite(m){const s=siteByName(m.site),angle=1.2;m.lat=s.lat+Math.cos(angle)*.0062;m.lng=s.lng+Math.sin(angle)*.0062;m.inside=false}
function applyScenario(m,phase){const since=minuteOfDay()-m.shiftStart;
 if(m.scenario==='connectivity'&&since>=115&&since<145){m.status='dark';m.signal='Offline';m.speed=0;if(!m.exception)raise(m,'connectivity','Machine signal lost during active hire','high');return true}
 if(m.scenario==='geofence-risk'&&since>=245&&since<285){operate(m,'moving');leaveSite(m);if(!m.exception)raise(m,'geofence',`Left permitted site: ${m.site}`,'high');return true}
 if(m.scenario==='idle-risk'&&since>=210&&since<255){operate(m,'idle');if(since>=225&&!m.exception)raise(m,'idle','Excessive idle time: 15+ minutes during hire','medium');return true}
 if(m.scenario==='service-risk'&&m.nextService-m.meter<=50&&!m.exception)raise(m,'maintenance',`Service due in ${Math.max(0,Math.round(m.nextService-m.meter))} h`,'medium');
 return false}
function simulateOne(m){const phase=phaseFor(m,minuteOfDay());setPhase(m,phase);const exceptionOwnsState=applyScenario(m,phase);if(!exceptionOwnsState){
  if(phase==='prestart'||phase==='shutdown')operate(m,'off');
  else if(phase==='mobilising'){operate(m,'moving');moveInsideSite(m)}
  else if(phase==='break')operate(m,m.scenario==='standby'?'off':'idle');
  else if(phase==='winddown')operate(m,'idle');
  else if(phase==='productive'){
    if(m.scenario==='standby')operate(m,'off');
    else if(m.scenario==='haul'){operate(m,'moving');moveInsideSite(m)}
    else{const cycle=(state.tick+Number(m.id.slice(1))*3)%18;operate(m,cycle<3?'idle':cycle<7?'moving':'running');if(m.status==='moving')moveInsideSite(m)}
  }
 }
 if(m.scenario==='connectivity'&&m.signal==='Live'&&m.exception?.type==='connectivity'&&!m.exception.ack){m.events.unshift({time:nowTime(new Date(state.clock)),type:'connectivity',text:'Machine connection restored — investigation still open'});m.exception.ack=true;const a=m.alerts.find(x=>x.type==='connectivity'&&!x.ack);if(a)a.ack=true}
 if(m.fuel<20)raise(m,'fuel',`Fuel low at ${Math.round(m.fuel)}%`,'medium');
 if(m.meter>=m.nextService)raise(m,'maintenance',`Service overdue by ${Math.round(m.meter-m.nextService)} h`,'high');
 if(state.tick%2===0&&m.signal==='Live'){m.trail.push({ts:state.clock,t:nowTime(new Date(state.clock)),lat:m.lat,lng:m.lng});m.trail=m.trail.slice(-180)}
 m.sensor.push({time:nowTime(new Date(state.clock)),fuel:+m.fuel.toFixed(1),temp:m.coolant});m.sensor=m.sensor.slice(-80);
 const hire=m.hire[0];hire.meterEnd=+m.meter.toFixed(2);hire.measured=+(hire.meterEnd-hire.meterStart).toFixed(2);hire.proposed=Math.max(hire.minimum,Math.ceil(hire.measured*4)/4);if(phase==='shutdown')hire.status=hire.status==='Approved'?'Approved':'Needs review';else if(hire.status==='Collecting evidence')hire.status='Collecting evidence'
}
function step(){state.clock+=60000;state.tick++;state.machines.forEach(simulateOne);save();renderAll()}
function selected(){return state.machines.find(m=>m.id===state.selected)||state.machines[0]}
function statusLabel(s){return s==='dark'?'Offline':s[0].toUpperCase()+s.slice(1)}
function filtered(){return state.machines.filter(m=>(state.filters.site==='all'||m.site===state.filters.site)&&(state.filters.type==='all'||m.type===state.filters.type)&&(state.filters.status==='all'||m.status===state.filters.status)&&(state.filters.customer==='all'||m.customer===state.filters.customer))}
function aggregate(){const ms=filtered(),connected=ms.filter(m=>m.signal==='Live'),working=ms.filter(m=>['running','moving'].includes(m.status)),idle=ms.filter(m=>m.status==='idle'),open=ms.reduce((n,m)=>n+m.alerts.filter(a=>!a.ack).length,0),service=ms.filter(m=>m.nextService-m.meter<=50).length;const util=ms.length?ms.reduce((n,m)=>{const d=m.history.at(-1);return n+Math.min(100,d.working/8*100)},0)/ms.length:0;return{total:ms.length,connected:connected.length,working:working.length,idle:idle.length,open,service,util}}
function options(values,current){return `<option value="all">All</option>${[...new Set(values)].sort().map(v=>`<option ${v===current?'selected':''}>${esc(v)}</option>`).join('')}`}
function renderFilters(){document.getElementById('filter-site').innerHTML=options(state.machines.map(m=>m.site),state.filters.site);document.getElementById('filter-type').innerHTML=options(state.machines.map(m=>m.type),state.filters.type);document.getElementById('filter-status').innerHTML=options(state.machines.map(m=>m.status),state.filters.status);document.getElementById('filter-customer').innerHTML=options(state.machines.map(m=>m.customer),state.filters.customer)}
function renderClock(){const el=document.getElementById('sim-clock');if(!el)return;el.innerHTML=`<span class="sim-live ${state.running?'':'sim-paused'}">${state.running?'LIVE SIMULATION':'PAUSED'}</span><strong>${nowLabel(new Date(state.clock))}</strong><small>1 real second = 1 simulated minute · operational workday</small>`;const b=document.getElementById('toggle-run');if(b)b.textContent=state.running?'Pause':'Resume'}
function renderKPIs(){const el=document.getElementById('sim-kpis');if(!el)return;const a=aggregate();el.innerHTML=[['Assets',a.total],['Connected',a.connected],['Working',a.working],['Idle',a.idle],['Utilisation',`${Math.round(a.util)}%`],['Service attention',a.service],['Open alerts',a.open]].map(([k,v])=>`<div class="sim-kpi"><span>${k}</span><strong>${v}</strong></div>`).join('')}
function renderTable(){const body=document.querySelector('#machine-table tbody');if(!body)return;body.innerHTML=filtered().map(m=>{const d=m.history.at(-1),service=m.nextService-m.meter;return`<tr data-id="${m.id}"><td><b>${esc(m.asset)}</b><small>${esc(m.model)}</small></td><td>${esc(m.type)}</td><td><span class="sim-status"><i class="sim-dot ${m.status}"></i>${statusLabel(m.status)}</span><small>${esc(m.phase)}</small></td><td>${esc(m.site)}<small>${esc(m.customer)}</small></td><td>${fmt(m.meter)} h</td><td>${Math.round(m.fuel)}%</td><td>${Math.round(Math.min(100,d.working/8*100))}%</td><td>${service<=0?'OVERDUE':`${Math.round(service)} h`}</td></tr>`}).join('')||'<tr><td colspan="8">No machines match these filters. <button id="sim-clear-hint" style="text-decoration:underline;background:transparent;border:0;color:#2872c7;cursor:pointer">Clear filters</button></td></tr>';document.getElementById('sim-clear-hint')?.addEventListener('click',()=>{state.filters={site:'all',type:'all',status:'all',customer:'all'};save();renderFilters();renderAll()});document.querySelectorAll('#machine-table tbody tr[data-id]').forEach(r=>r.onclick=e=>{if(e.target.closest('a,button'))return;location.href=`./machine.html?id=${encodeURIComponent(r.dataset.id)}&view=overview`})}
function openAlerts(){return filtered().flatMap(m=>m.alerts.filter(a=>!a.ack).map(a=>({...a,machine:m}))).sort((a,b)=>a.severity==='high'?-1:1).slice(0,12)}
function renderQueue(){const host=document.getElementById('action-queue');if(!host)return;const list=openAlerts();host.innerHTML=list.length?list.map(a=>`<li><div class="sim-queue-top"><div><b>${esc(a.machine.asset)} · ${esc(a.text)}</b><small>${esc(a.time)} · ${esc(a.machine.site)}</small></div><span class="sim-severity ${a.severity}">${a.severity}</span></div><div class="sim-action-row"><button data-investigate="${a.machine.id}">Investigate</button><button data-ack="${a.machine.id}|${a.id}">Acknowledge</button>${a.type==='maintenance'?`<button data-service="${a.machine.id}">Schedule service</button>`:''}<button data-assign="${a.machine.id}">Assign</button></div></li>`).join(''):'<li><b>No open exceptions</b><small>Fleet activity is currently within expected conditions.</small></li>';document.querySelectorAll('[data-investigate]').forEach(b=>b.onclick=()=>{location.href=`./machine.html?id=${encodeURIComponent(b.dataset.investigate)}&view=alerts`});document.querySelectorAll('[data-ack]').forEach(b=>b.onclick=()=>{const [mid,aid]=b.dataset.ack.split('|'),m=state.machines.find(x=>x.id===mid),a=m?.alerts.find(x=>x.id===aid);if(a)a.ack=true;if(m?.exception)m.exception.ack=true;logAction('Acknowledge',m,a?.text||'Alert')});document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>logAction('Schedule service',state.machines.find(x=>x.id===b.dataset.service),'Maintenance work order'));document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>logAction('Assign',state.machines.find(x=>x.id===b.dataset.assign),'Assigned to fleet operations'))}
function historyRows(items,cols){return `<table class="history-table"><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${items.map(x=>`<tr>${cols.map(c=>`<td>${esc(typeof c[1]==='function'?c[1](x):x[c[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function overviewPanel(m){const service=m.nextService-m.meter;return`<div class="detail-columns"><section class="detail-block"><h3>Current operation</h3><ul class="detail-list"><li><span>Phase</span><b>${esc(m.phase)}</b></li><li><span>Status</span><b>${statusLabel(m.status)}</b></li><li><span>Signal</span><b>${esc(m.signal)}</b></li><li><span>Expected site</span><b>${esc(m.site)}</b></li><li><span>Exception</span><b>${m.exception&&!m.exception.ack?esc(m.exception.text):'None open'}</b></li></ul></section><section class="detail-block"><h3>Identity & assignment</h3><ul class="detail-list"><li><span>Type</span><b>${esc(m.type)}</b></li><li><span>Model</span><b>${esc(m.model)}</b></li><li><span>Serial</span><b>${esc(m.serial)}</b></li><li><span>Year</span><b>${m.year}</b></li><li><span>Attachment</span><b>${esc(m.attachment)}</b></li></ul></section><section class="detail-block"><h3>Hire & maintenance</h3><ul class="detail-list"><li><span>Customer</span><b>${esc(m.customer)}</b></li><li><span>Rate</span><b>R${m.rate}/h</b></li><li><span>Last service</span><b>${esc(m.lastService)}</b></li><li><span>Next service</span><b>${service<=0?'Overdue':Math.round(service)+' h remaining'}</b></li></ul></section><section class="detail-block"><h3>Machine readings</h3><ul class="detail-list"><li><span>Engine load</span><b>${m.engineLoad===null?'Not available':m.engineLoad+'%'}</b></li><li><span>Coolant</span><b>${m.coolant===null?'Not available':m.coolant+' °C'}</b></li><li><span>Fuel</span><b>${Math.round(m.fuel)}%</b></li></ul></section></div>`}
function activityPanel(m){return`<div class="detail-columns"><section class="detail-block"><h3>7-day run vs idle</h3><div class="mini-bars">${m.history.map(d=>`<div class="mini-bar"><span>${d.date}</span><div class="mini-track"><div class="mini-fill" style="width:${clamp(d.working/8*100,0,100)}%"></div></div><b>${fmt(d.working)}h</b><span></span><div class="mini-track"><div class="mini-fill idle" style="width:${clamp(d.idle/3*100,0,100)}%"></div></div><b>${fmt(d.idle)}h</b></div>`).join('')}</div></section><section class="detail-block"><h3>Operational timeline</h3>${historyRows(m.events.slice(0,24),[['Time','time'],['Type','type'],['Event','text']])}</section></div>`}
function maintenancePanel(m){return`<div class="detail-columns"><section class="detail-block"><h3>Maintenance events</h3>${historyRows(m.maintenance,[['Date','date'],['Work','work'],['Meter',x=>x.meter+' h'],['Status','status']])}</section><section class="detail-block"><h3>Service position</h3><ul class="detail-list"><li><span>Current meter</span><b>${fmt(m.meter)} h</b></li><li><span>Next target</span><b>${fmt(m.nextService)} h</b></li><li><span>Remaining</span><b>${Math.round(m.nextService-m.meter)} h</b></li></ul></section></div>`}
function hirePanel(m){const h=m.hire[0],value=h.proposed*m.rate;return`<div class="recon-box"><div class="recon-item"><span>Measured hours</span><strong>${fmt(h.measured)} h</strong></div><div class="recon-item"><span>Minimum hire</span><strong>${h.minimum} h</strong></div><div class="recon-item"><span>Proposed billable</span><strong>${fmt(h.proposed)} h</strong></div><div class="recon-item"><span>Proposed value</span><strong>R${Math.round(value).toLocaleString('en-ZA')}</strong></div></div><div class="detail-block" style="margin-top:14px"><h3>Commercial state</h3><p>${esc(h.status)}. Measured operating evidence remains separate from what is approved for billing.</p><div class="sim-action-row"><button data-detail-action="Approve proposed hours">Approve proposed hours</button><button data-detail-action="Flag discrepancy">Flag discrepancy</button><button data-detail-action="Request site confirmation">Request site confirmation</button></div></div>`}
function alertsPanel(m){return m.alerts.length?historyRows(m.alerts,[['Time','time'],['Type','type'],['Alert','text'],['Status',x=>x.ack?'Acknowledged':'Open']]):'<p>No alerts yet.</p>'}
function sensorsPanel(m){return historyRows(m.sensor.slice(-20).reverse(),[['Time','time'],['Fuel',x=>x.fuel+'%'],['Coolant',x=>x.temp===null?'Not available':x.temp+' °C']])}
function renderDetail(tab='overview'){const host=document.getElementById('machine-detail');if(!host)return;const m=selected(),d=m.history.at(-1),service=m.nextService-m.meter;host.innerHTML=`<div class="detail-top"><div><span class="sim-status"><i class="sim-dot ${m.status}"></i>${statusLabel(m.status)}</span><h2>${esc(m.asset)} · ${esc(m.model)}</h2><p>${esc(m.site)} · ${esc(m.customer)} · ${esc(m.phase)}</p></div><div class="detail-meta"><b>${m.signal}</b><span>${m.lat.toFixed(5)}, ${m.lng.toFixed(5)}</span></div></div><div class="detail-grid"><div class="detail-stat"><span>Hour meter</span><strong>${fmt(m.meter)} h</strong></div><div class="detail-stat"><span>Fuel</span><strong>${Math.round(m.fuel)}%</strong></div><div class="detail-stat"><span>Today run</span><strong>${fmt(d.run)} h</strong></div><div class="detail-stat"><span>Today idle</span><strong>${fmt(d.idle)} h</strong></div><div class="detail-stat"><span>Service</span><strong>${service<=0?'Overdue':Math.round(service)+' h'}</strong></div><div class="detail-stat"><span>Open alerts</span><strong>${m.alerts.filter(a=>!a.ack).length}</strong></div></div><div class="detail-tabs">${[['overview','Overview'],['activity','History'],['maintenance','Maintenance'],['hire','Hire reconciliation'],['alerts','Alerts'],['sensors','Readings']].map(([id,label])=>`<button data-tab="${id}" class="${id===tab?'active':''}">${label}</button>`).join('')}</div><div class="detail-panel">${tab==='overview'?overviewPanel(m):tab==='activity'?activityPanel(m):tab==='maintenance'?maintenancePanel(m):tab==='hire'?hirePanel(m):tab==='alerts'?alertsPanel(m):sensorsPanel(m)}</div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>renderDetail(b.dataset.tab));document.querySelectorAll('[data-detail-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.detailAction;if(a==='Approve proposed hours')m.hire[0].status='Approved';if(a==='Flag discrepancy')m.hire[0].status='Discrepancy';logAction(a,m,'Hire review');renderDetail(tab)})}
function initMap(){if(!window.L||map||!document.getElementById('fleet-map'))return;map=L.map('fleet-map',{zoomControl:true}).setView([-25.97,28.12],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);Object.values(sites).forEach(s=>geofenceLayers.push(L.circle([s.lat,s.lng],{radius:s.radius*90000,weight:1,fillOpacity:.03}).addTo(map).bindTooltip(s.name)))}
function renderMap(){initMap();if(!map)return;const visible=new Set(filtered().map(m=>m.id));state.machines.forEach(m=>{let marker=markers.get(m.id);if(!marker){marker=L.circleMarker([m.lat,m.lng],{radius:7,weight:2,fillOpacity:.9}).addTo(map).on('click',()=>{state.selected=m.id;save();renderAll()});markers.set(m.id,marker)}marker.setLatLng([m.lat,m.lng]);if(visible.has(m.id)){if(!map.hasLayer(marker))marker.addTo(map)}else if(map.hasLayer(marker))map.removeLayer(marker);marker.bindTooltip(`${m.asset} · ${statusLabel(m.status)} · ${m.phase}`)});if(trailLayer)map.removeLayer(trailLayer);const m=selected();if(m.trail.length>1)trailLayer=L.polyline(m.trail.map(p=>[p.lat,p.lng]),{weight:3,opacity:.7}).addTo(map);requestAnimationFrame(()=>map.invalidateSize())}
function toast(text){let t=document.querySelector('.sim-toast');if(!t){t=document.createElement('div');t.className='sim-toast';document.body.append(t)}t.textContent=text;clearTimeout(t._timer);t._timer=setTimeout(()=>t.remove(),2200)}
function renderAll(){renderClock();renderKPIs();renderTable();renderQueue();renderDetail(document.querySelector('.detail-tabs .active')?.dataset.tab||'overview');renderMap()}
function bindStatic(){['site','type','status','customer'].forEach(k=>document.getElementById('filter-'+k)?.addEventListener('change',e=>{state.filters[k]=e.target.value;save();renderAll()}));document.getElementById('toggle-run')?.addEventListener('click',()=>{state.running=!state.running;save();renderClock()});document.getElementById('step-once')?.addEventListener('click',step);document.getElementById('reset-sim')?.addEventListener('click',()=>{localStorage.removeItem(SIM_KEY);localStorage.removeItem(ACTION_KEY);state=initialState();save();renderFilters();renderAll();toast('Fleet day reset')});document.getElementById('clear-filters')?.addEventListener('click',()=>{state.filters={site:'all',type:'all',status:'all',customer:'all'};save();renderFilters();renderAll()})}
renderFilters();bindStatic();renderAll();setInterval(()=>{if(state.running)step()},1000);